// Generated by design-sync setup, then committed. `@workspace/ui` ships as
// source with wildcard subpath exports and no dist, so the converter has no
// single entry to bundle — this barrel is it.
//
// Eight modules are deliberately absent: they reach Shiki's language
// grammars, mermaid and katex, which measured 29.4 MB against the upload's
// 12 MB per-file cap. See NOTES.md; regenerate with the snippet there.

export * from "../packages/ui/src/components/accordion";
export * from "../packages/ui/src/components/ai-elements/conversation";
export * from "../packages/ui/src/components/ai-elements/message";
export * from "../packages/ui/src/components/ai-elements/reasoning";
export { Shimmer } from "../packages/ui/src/components/ai-elements/shimmer";
export * from "../packages/ui/src/components/alert-dialog";
export * from "../packages/ui/src/components/alert";
export * from "../packages/ui/src/components/avatar";
export * from "../packages/ui/src/components/badge";
export * from "../packages/ui/src/components/button-group";
export * from "../packages/ui/src/components/button";
export * from "../packages/ui/src/components/card";
export * from "../packages/ui/src/components/collapsible";
export * from "../packages/ui/src/components/command";
export * from "../packages/ui/src/components/custom/model-switch-boundary";
export * from "../packages/ui/src/components/custom/text-shimmer";
export * from "../packages/ui/src/components/dialog";
export * from "../packages/ui/src/components/dropdown-menu";
export * from "../packages/ui/src/components/field";
export * from "../packages/ui/src/components/form";
export * from "../packages/ui/src/components/hover-card";
export * from "../packages/ui/src/components/input-group";
export * from "../packages/ui/src/components/input";
export * from "../packages/ui/src/components/kbd";
export * from "../packages/ui/src/components/label";
export * from "../packages/ui/src/components/marker";
export * from "../packages/ui/src/components/popover";
export * from "../packages/ui/src/components/scroll-area";
export * from "../packages/ui/src/components/select";
export * from "../packages/ui/src/components/separator";
export * from "../packages/ui/src/components/sheet";
export * from "../packages/ui/src/components/sidebar";
export * from "../packages/ui/src/components/skeleton";
export * from "../packages/ui/src/components/sonner";
export * from "../packages/ui/src/components/spinner";
export * from "../packages/ui/src/components/switch";
export * from "../packages/ui/src/components/tabs";
export * from "../packages/ui/src/components/textarea";
export * from "../packages/ui/src/components/toggle-group";
export * from "../packages/ui/src/components/toggle";
export * from "../packages/ui/src/components/tooltip";

// The class-name helper every component composes with.
export { cn } from "../packages/ui/src/lib/utils";
