import { InferSelectModel, sql } from 'drizzle-orm';
import {
  customType,
  integer,
  pgEnum,
  pgPolicy,
  pgTable,
  primaryKey,
  text,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';

import { timestamptz } from '../columns';
import { users } from './auth';

// drizzle-orm/pg-core has no `bytea` column; postgres.js maps it to a Buffer
// in both directions.
const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return 'bytea';
  },
});

export const mediaProvenance = pgEnum('media_provenance', [
  'upload',
  'read',
  'prompt-import',
]);

export const mediaVariant = pgEnum('media_variant', ['original', 'model']);

// One owner-owned image (vision-media D1). `id` is a UUIDv7 generated by the
// API (`uuid` package `v7()`): neither PostgreSQL 17 nor Node 22 provides one,
// so the column has no default. Top-level format/size/dimensions describe the
// original; the `model_*` columns describe the normalized model variant. The
// bytes live in `media_blobs`, so a later object-storage move replaces only
// that table. `sha256` is the hex digest of the original and deduplicates
// within one owner only.
//
// Media is immutable and never deleted by the application: there is no UPDATE
// or DELETE policy, so under FORCE RLS no tenant-scoped statement can change
// or remove a row. Rows still cascade when their owner user is deleted
// (referential actions are not subject to row security).
//
// NOTE: `.enableRLS()` only emits ENABLE. The migration ALSO issues
// `FORCE ROW LEVEL SECURITY` for both tables (src/db/AGENTS.md P1). Re-add
// FORCE if the migration is regenerated.
export const mediaObjects = pgTable(
  'media_objects',
  {
    id: uuid('id').primaryKey(),
    ownerUserId: text('owner_user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    provenance: mediaProvenance('provenance').notNull(),
    name: text('name').notNull(),
    mediaType: text('media_type').notNull(),
    width: integer('width').notNull(),
    height: integer('height').notNull(),
    byteSize: integer('byte_size').notNull(),
    modelMediaType: text('model_media_type').notNull(),
    modelWidth: integer('model_width').notNull(),
    modelHeight: integer('model_height').notNull(),
    modelByteSize: integer('model_byte_size').notNull(),
    sha256: text('sha256').notNull(),
    createdAt: timestamptz('created_at').notNull().defaultNow(),
  },
  (t) => [
    // Per-owner dedup, concurrency-safe: a racing identical ingest hits this
    // constraint and reuses the winner's row.
    unique('media_objects_owner_sha256_unique').on(t.ownerUserId, t.sha256),
    pgPolicy('media_objects_owner_select', {
      for: 'select',
      using: sql`owner_user_id = current_setting('app.current_user_id', true)`,
    }),
    pgPolicy('media_objects_owner_insert', {
      for: 'insert',
      withCheck: sql`owner_user_id = current_setting('app.current_user_id', true)`,
    }),
  ],
).enableRLS();

// The `original` and `model` bytes of a media object. Access follows the
// parent object's owner through a subquery that itself runs under
// `media_objects` RLS, so a blob is visible or insertable only for an object
// the current owner can see. Immutable like its parent: no UPDATE or DELETE
// policy.
export const mediaBlobs = pgTable(
  'media_blobs',
  {
    mediaId: uuid('media_id')
      .notNull()
      .references(() => mediaObjects.id, { onDelete: 'cascade' }),
    variant: mediaVariant('variant').notNull(),
    data: bytea('data').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.mediaId, t.variant] }),
    pgPolicy('media_blobs_owner_select', {
      for: 'select',
      using: sql`media_id IN (
        SELECT id FROM media_objects
        WHERE owner_user_id = current_setting('app.current_user_id', true)
      )`,
    }),
    pgPolicy('media_blobs_owner_insert', {
      for: 'insert',
      withCheck: sql`media_id IN (
        SELECT id FROM media_objects
        WHERE owner_user_id = current_setting('app.current_user_id', true)
      )`,
    }),
  ],
).enableRLS();

export type MediaObject = InferSelectModel<typeof mediaObjects>;
export type MediaProvenance = (typeof mediaProvenance.enumValues)[number];
export type MediaVariant = (typeof mediaVariant.enumValues)[number];
