-- Anchor the last two naive timestamp columns to UTC.
--
-- Both are auth.js-derived scaffolding that predates the rest of the schema and
-- were declared without `withTimezone: true`, so their meaning depended on the
-- session zone of whichever process wrote them. `users.email_verified` is
-- reachable: `users.service.ts` maps it into `PublicUserResponse`, so the wrong
-- type was in the public API contract (nothing writes it yet, so every existing
-- value is NULL and the conversion is a no-op on real data).
--
-- Generated by drizzle-kit after schema/*.ts moved to the `timestamptz()` helper
-- in src/db/columns.ts. That refactor is DDL-neutral for the other 38 columns,
-- which is why this migration touches only these two.
--
-- `verification_tokens` has no reader anywhere outside the schema file; it is
-- vestigial and a candidate for deletion under the pre-launch evolution policy,
-- which is a separate decision from correcting its type here.
ALTER TABLE "users" ALTER COLUMN "email_verified" SET DATA TYPE timestamp with time zone USING "email_verified" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "verification_tokens" ALTER COLUMN "expires" SET DATA TYPE timestamp with time zone USING "expires" AT TIME ZONE 'UTC';
